name: archlinux-base

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 2 2 * *'

jobs:
  build-and-push:
    runs-on: act_runner
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Meta
        id: meta
        run: |
          echo "BUILD_DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          echo "DATE_TAG=$(date +'%y%m')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          registry: docker.io

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.base
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          provenance: false
          annotations: |
            org.opencontainers.image.title=casjaysdev/archlinux
            org.opencontainers.image.description=Containerized version of casjaysdev/archlinux
            org.opencontainers.image.vendor=CasjaysDev
            org.opencontainers.image.authors=CasjaysDev <docker-admin@casjaysdev.pro>
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=latest
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          tags: |
            docker.io/casjaysdev/archlinux:latest
            docker.io/casjaysdev/archlinux:${{ steps.meta.outputs.DATE_TAG }}
